### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by mikldt** [concerto/bandshell#30]
Per issue #24, bandshell fails silently on some PCs because the server is not accessible if it binds to an IPv6 interface but not an IPv4 interface.  I recently encountered this problem on the latest LinuxMint distribution, so it is not esoteric. Can we remove the IPv6 bind statement without interrupting potential IPv6 functionality?

**Comment by fjaeckel** [comment]
A behaviour that I deem intended as described in more detail here: https://netcheck.poly.edu/projects/project/wiki/WebrickTests#bind6

I personally see binding on IPv6-only generally not a bad thing, however you can influence the bahaviour with `sysctl -w net.ipv6.bindv6only=0` on a Linux system.

However on a ruby 2.3 system with newest libraries, I see this stack trace causing a curl on `http://localhost:4567/system_password`

```[2017-01-26 14:27:55] INFO  WEBrick::HTTPServer#start: pid=14324 port=4567
2017-01-26 14:27:59 - NoMethodError - undefined method `to_u32' for #<IPAddress::IPv6:0x007f183c435a98>
Did you mean?  to_u128:
        /var/lib/gems/2.3.0/gems/ipaddress-0.8.3/lib/ipaddress/ipv4.rb:512:in `<=>'
        /var/lib/gems/2.3.0/gems/bandshell-1.7.1/lib/bandshell/application/app.rb:99:in `=='
        /var/lib/gems/2.3.0/gems/bandshell-1.7.1/lib/bandshell/application/app.rb:99:in `include?'
        /var/lib/gems/2.3.0/gems/bandshell-1.7.1/lib/bandshell/application/app.rb:99:in `request_is_local?'
        /var/lib/gems/2.3.0/gems/bandshell-1.7.1/lib/bandshell/application/app.rb:111:in `authorized?'
        /var/lib/gems/2.3.0/gems/bandshell-1.7.1/lib/bandshell/application/app.rb:90:in `protected!'
        /var/lib/gems/2.3.0/gems/bandshell-1.7.1/lib/bandshell/application/app.rb:402:in `block in <class:ConcertoConfigServer>'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/nulllogger.rb:9:in `call'
        /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
        /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
::1 - - [26/Jan/2017:14:27:59 CET] "GET /system_password HTTP/1.1" 500 30`
